// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ssagen

import (
	"cmd/compile/internal/ir"
	"cmd/compile/internal/ssa"
	"cmd/compile/internal/types"
	"cmd/internal/src"
)

// spmdForStmt generates SSA for an SPMD "go for" loop.
//
// Phase 1.10c: Vectorized loop structure. The walk/range.go phase has
// already lowered the range clause into Init/Cond/Post/Body with the correct
// laneCount stride. We generate the same loop structure as scalar loops:
//
//	Init: hv1 = 0; hn = N                          (from walk)
//	Cond: hv1 < hn                                  (from walk, bounds check)
//	Body: i = OSPMDAdd(OSPMDSplat(hv1), OSPMDLaneIndex()) (from walk)
//	      user code                                 (from walk)
//	Post: hv1 = hv1 + laneCount                     (from walk)
//
// When N is not a multiple of laneCount, the last iteration processes
// fewer than laneCount elements. spmdBodyWithTailMask handles tail masking
// by computing a per-iteration mask (laneIndex < bound) to disable
// out-of-bounds lanes.
func (s *state) spmdForStmt(n *ir.ForStmt) {
	laneCount := n.LaneCount
	if laneCount <= 1 {
		// No vectorization benefit, fall back to scalar loop.
		s.scalarForStmt(n)
		return
	}

	// Save and set SPMD context
	prevInSPMD := s.inSPMDLoop
	prevMask := s.spmdMask
	s.inSPMDLoop = true
	// Initialize all-true mask: SPMDSplat(true)
	boolType := types.Types[types.TBOOL]
	s.spmdMask = s.newValue1(ssa.OpSPMDSplat, boolType, s.constBool(true))
	defer func() {
		s.inSPMDLoop = prevInSPMD
		s.spmdMask = prevMask
	}()

	bCond := s.f.NewBlock(ssa.BlockPlain)
	bBody := s.f.NewBlock(ssa.BlockPlain)
	bIncr := s.f.NewBlock(ssa.BlockPlain)
	bEnd := s.f.NewBlock(ssa.BlockPlain)

	// ensure empty for loops have correct position; issue #30167
	bBody.Pos = n.Pos()

	// first, jump to condition test
	b := s.endBlock()
	b.AddEdgeTo(bCond)

	// generate code to test condition
	s.startBlock(bCond)
	if n.Cond != nil {
		s.condBranch(n.Cond, bBody, bEnd, 1)
	} else {
		b := s.endBlock()
		b.Kind = ssa.BlockPlain
		b.AddEdgeTo(bBody)
	}

	// set up for continue/break in body
	prevContinue := s.continueTo
	prevBreak := s.breakTo
	s.continueTo = bIncr
	s.breakTo = bEnd
	var lab *ssaLabel
	if sym := n.Label; sym != nil {
		lab = s.label(sym)
		lab.continueTarget = bIncr
		lab.breakTarget = bEnd
	}

	// generate body
	s.startBlock(bBody)
	s.spmdBodyWithTailMask(n)

	// tear down continue/break
	s.continueTo = prevContinue
	s.breakTo = prevBreak
	if lab != nil {
		lab.continueTarget = nil
		lab.breakTarget = nil
	}

	// done with body, goto incr
	if b := s.endBlock(); b != nil {
		b.AddEdgeTo(bIncr)
	}

	// generate incr (walk already set correct stride)
	s.startBlock(bIncr)
	if n.Post != nil {
		s.stmt(n.Post)
	}
	if b := s.endBlock(); b != nil {
		b.AddEdgeTo(bCond)
		// It can happen that bIncr ends in a block containing only VARKILL,
		// and that muddles the debugging experience.
		if b.Pos == src.NoXPos {
			b.Pos = bCond.Pos
		}
	}

	s.startBlock(bEnd)
}

// spmdBodyWithTailMask generates the SPMD loop body with per-iteration tail masking.
// For a loop `go for i := range N` with laneCount L, when N is not a multiple of L,
// the last iteration has lane indices that exceed N. This function computes a tail
// mask (laneIndex < bound) each iteration and applies it to the execution mask so
// out-of-bounds lanes are disabled.
//
// The body generation proceeds as:
//  1. Reset s.spmdMask to all-true (clean slate each iteration)
//  2. Execute n.Body[0] — the SPMD index assignment (i = SPMDAdd(SPMDSplat(hv1), SPMDLaneIndex()))
//  3. Compute tailMask = SPMDLess(laneIndices, SPMDSplat(bound))
//  4. Apply s.spmdMask = SPMDMaskAnd(allTrue, tailMask)
//  5. Execute n.Body[1:] — remaining user code with correct mask
func (s *state) spmdBodyWithTailMask(n *ir.ForStmt) {
	boolType := types.Types[types.TBOOL]

	// Reset mask to all-true at start of each iteration.
	s.spmdMask = s.newValue1(ssa.OpSPMDSplat, boolType, s.constBool(true))

	if n.Cond == nil || len(n.Body) == 0 {
		s.stmtList(n.Body)
		return
	}

	// Execute the first body statement (SPMD index assignment: i = SPMDAdd(SPMDSplat(hv1), SPMDLaneIndex()))
	firstStmt := n.Body[0]
	s.stmt(firstStmt)

	// Validate SPMD assignment pattern: i = SPMDAdd(SPMDSplat(hv1), SPMDLaneIndex())
	// If the pattern doesn't match, skip tail masking (safe fallback: all-true mask).
	assignStmt, ok := firstStmt.(*ir.AssignStmt)
	if !ok || assignStmt.Y == nil || assignStmt.Y.Op() != ir.OSPMDAdd {
		s.stmtList(n.Body[1:])
		return
	}

	// Validate condition structure: hv1 < hn (generated by walk/range.go)
	condExpr, ok := n.Cond.(*ir.BinaryExpr)
	if !ok || condExpr.Op() != ir.OLT {
		s.stmtList(n.Body[1:])
		return
	}

	// Get SSA value of the loop variable (just assigned above)
	loopVar := assignStmt.X
	iVal := s.variable(loopVar, loopVar.Type())

	// Extract bound from Cond: hv1 < hn → hn is the Y operand
	boundVal := s.expr(condExpr.Y)

	// Splat bound to all lanes and compare: tailMask = (i < bound)
	splatBound := s.newValue1(ssa.OpSPMDSplat, loopVar.Type(), boundVal)
	tailMask := s.newValue2(ssa.OpSPMDLess, boolType, iVal, splatBound)

	// Apply tail mask to execution mask
	s.spmdMask = s.newValue2(ssa.OpSPMDMaskAnd, boolType, s.spmdMask, tailMask)

	// Execute remaining body statements with tail-masked execution
	s.stmtList(n.Body[1:])
}

// scalarForStmt generates a standard scalar for loop (same as normal OFOR).
// Used as fallback when laneCount <= 1 or vectorization is not beneficial.
func (s *state) scalarForStmt(n *ir.ForStmt) {
	bCond := s.f.NewBlock(ssa.BlockPlain)
	bBody := s.f.NewBlock(ssa.BlockPlain)
	bIncr := s.f.NewBlock(ssa.BlockPlain)
	bEnd := s.f.NewBlock(ssa.BlockPlain)

	bBody.Pos = n.Pos()

	b := s.endBlock()
	b.AddEdgeTo(bCond)

	s.startBlock(bCond)
	if n.Cond != nil {
		s.condBranch(n.Cond, bBody, bEnd, 1)
	} else {
		b := s.endBlock()
		b.Kind = ssa.BlockPlain
		b.AddEdgeTo(bBody)
	}

	prevContinue := s.continueTo
	prevBreak := s.breakTo
	s.continueTo = bIncr
	s.breakTo = bEnd
	var lab *ssaLabel
	if sym := n.Label; sym != nil {
		lab = s.label(sym)
		lab.continueTarget = bIncr
		lab.breakTarget = bEnd
	}

	s.startBlock(bBody)
	s.stmtList(n.Body)

	s.continueTo = prevContinue
	s.breakTo = prevBreak
	if lab != nil {
		lab.continueTarget = nil
		lab.breakTarget = nil
	}

	if b := s.endBlock(); b != nil {
		b.AddEdgeTo(bIncr)
	}

	s.startBlock(bIncr)
	if n.Post != nil {
		s.stmt(n.Post)
	}
	if b := s.endBlock(); b != nil {
		b.AddEdgeTo(bCond)
		if b.Pos == src.NoXPos {
			b.Pos = bCond.Pos
		}
	}

	s.startBlock(bEnd)
}

// spmdIfStmt generates SSA for a varying-condition if/else inside an SPMD loop.
// Instead of branching, both branches execute with different lane masks,
// and modified variables are merged using SPMDSelect.
func (s *state) spmdIfStmt(n *ir.IfStmt) {
	// Evaluate the varying condition (including any init statements)
	s.stmtList(n.Cond.Init())
	condValue := s.expr(n.Cond)
	boolType := types.Types[types.TBOOL]

	savedMask := s.spmdMask

	// Compute branch masks
	trueMask := s.newValue2(ssa.OpSPMDMaskAnd, boolType, savedMask, condValue)
	falseMask := s.newValue2(ssa.OpSPMDMaskAndNot, boolType, savedMask, condValue)

	// Snapshot vars before branches
	snapshot := s.snapshotVars()

	// Execute true branch with trueMask
	s.spmdMask = trueMask
	s.stmtList(n.Body)
	trueVars := s.snapshotVars()

	// Restore to pre-branch state, execute false branch with falseMask
	s.restoreVarsSnapshot(snapshot)
	s.spmdMask = falseMask
	if len(n.Else) > 0 {
		s.stmtList(n.Else)
	}
	// s.vars now holds false-branch state

	// Merge modified variables using SPMDSelect
	s.spmdMergeVars(condValue, snapshot, trueVars)

	// Restore mask
	s.spmdMask = savedMask
}

// snapshotVars returns a shallow copy of the current variable map.
func (s *state) snapshotVars() map[ir.Node]*ssa.Value {
	snap := make(map[ir.Node]*ssa.Value, len(s.vars))
	for k, v := range s.vars {
		snap[k] = v
	}
	return snap
}

// restoreVarsSnapshot restores s.vars from a snapshot.
func (s *state) restoreVarsSnapshot(snap map[ir.Node]*ssa.Value) {
	s.vars = make(map[ir.Node]*ssa.Value, len(snap))
	for k, v := range snap {
		s.vars[k] = v
	}
}

// spmdMergeVars merges variables after both branches of a varying if.
// condValue is the varying bool condition.
// snapshot is the pre-branch variable state.
// trueVars is the variable state after the true branch.
// s.vars currently holds the false-branch state.
//
// For each variable modified in either branch:
//   merged = SPMDSelect(cond, trueVal, falseVal)
func (s *state) spmdMergeVars(condValue *ssa.Value, snapshot, trueVars map[ir.Node]*ssa.Value) {
	// Collect all variables that were modified in either branch
	for varNode, trueVal := range trueVars {
		origVal := snapshot[varNode]
		falseVal := s.vars[varNode]
		if falseVal == nil {
			falseVal = origVal
		}
		if origVal == nil && falseVal == nil {
			// New variable only exists in true branch; not visible after merge
			continue
		}
		if trueVal == origVal && falseVal == origVal {
			continue // not modified in either branch
		}
		if trueVal == falseVal {
			s.vars[varNode] = trueVal // same value, no select needed
			continue
		}
		// Different values: merge with SPMDSelect(cond, trueVal, falseVal)
		s.vars[varNode] = s.newValue3(ssa.OpSPMDSelect, trueVal.Type, condValue, trueVal, falseVal)
	}
	// Also check false-only modifications (vars modified in false branch but not in true)
	for varNode, falseVal := range s.vars {
		if _, inTrue := trueVars[varNode]; inTrue {
			continue // already handled above
		}
		origVal := snapshot[varNode]
		if falseVal == origVal {
			continue // not modified
		}
		trueVal := origVal
		if trueVal == nil {
			continue // new variable only in false branch, keep it
		}
		s.vars[varNode] = s.newValue3(ssa.OpSPMDSelect, falseVal.Type, condValue, trueVal, falseVal)
	}
}
